### ISSUE TITLE
Exporting from ASCAM into .mat file doesn't export everything.

### ISSUE THREAD

**Issue by eckuru** [AGPlested/ASCAM#16]
I want to export data from ASCAM into a .mat file after doing baseline correction and filtering. When I do this and load the file in MATLAB, only one variable `time` is loaded (1x4000 double). Somehow when I open the file in ASCAM I get the complete data, baseline corrected and filtered.

**Comment by imLew** [comment]
This was never actually tested with matlab. I just assumed the[ `scipy.io.savemat`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.savemat.html) function would handle it correctly.

Since I don't have access to matlab I can't really fix this. If you have some time to figure out how to make that function produce files that matlab can read it should be pretty easy to change [here](https://github.com/AGPlested/ASCAM/blob/970c60f2d41eeeeed16bbd20b18fc3c41f4d53c9/src/core/recording.py#L436-L485).

**Comment by eckuru** [comment]
Apparently it's just that `export_dict` can't have spaces in dictionary keys, probably because those are variable names after importing to Matlab.
